#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置 dev prod
---
server:
  port: 6001 #端口号
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-config-eureka-001
eureka:
  instance:
#     hostname: 47.103.15.103
    hostname: eureka6001.com
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
#       defaultZone: http://${eureka.instance.hostname}:6002/eureka/
      defaultZone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: false # 禁用自我保护机制*****************
#     eviction-interval-timer-in-ms: 100

---
server:
  port: 60011 #端口号
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-config-eureka-001
eureka:
  instance:
#     hostname: 47.103.15.103
    hostname: eureka6001.com
  client:
    registerWithEureka: false 
    fetchRegistry: false 
    serviceUrl:
#       defaultZone: http://${eureka.instance.hostname}:6002/eureka/
      defaultZone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: true # 开启自我保护机制*****************
#     eviction-interval-timer-in-ms: 100
#保存时注意，选择 UTF-8 保存
