#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8101
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml 
  type-aliases-package: com.yangpeng.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product			# ******服务名*******microservice-product-config
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#     driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
#     url: jdbc:mysql://47.103.15.103:3306/springcloud_db01?serverTimezone=GMT%2B8&characterEncoding=UTF-8 #数据库连接地址，*****注意库名 db01***************
    url: jdbc:mysql://192.168.199.190:4010/TESTDB?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  instance:
#     hostname: 47.103.15.103
#     hostname: eureka6001.com
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#       defaultZone: http://${eureka.instance.hostname}:6001/eureka,http://${eureka.instance.hostname}:6002/eureka
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
---
server:
  port: 8101
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml 
  type-aliases-package: com.yangpeng.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-product			# ******服务名*******microservice-product-config
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#     driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
#     url: jdbc:mysql://47.103.15.103:3306/springcloud_db02?serverTimezone=GMT%2B8&characterEncoding=UTF-8 #数据库连接地址，*****注意库名 db02***************
    url: jdbc:mysql://192.168.199.190:4010/TESTDB?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  instance:
#     hostname: 47.103.15.103
#     hostname: eureka6001.com
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
#       defaultZone: http://${eureka.instance.hostname}:6001/eureka,http://${eureka.instance.hostname}:6002/eureka
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
emp:
  name: zhangsan33
